<section>
    <h1>Pojištěnci</h1>
    <table class="table-sm">
        <tr>
            <td>Příjmení</td>
            <td>Jméno</td>
            <td>Telefon</td>
            <td>Věk</td>
        </tr>
        <?php foreach ($customers as $customer) : ?>
            <tr>
                <td><?= $customer['surname'] ?></td>
                <td><?= $customer['name'] ?></td>
                <td><?= $customer['tel'] ?></td>
                <td><?= $customer['age'] ?></td>
            </tr>
        <?php endforeach ?>
    </table>
</section>
<hr>
<section>
    <h1>Nový pojištěnec</h1>
    <?php
        if (!empty($customer['message'])) {
            echo("<p>" . $customer['message'] . "<p>");
        }
        
        $name = (isset($_POST['name'])) ? $_POST['name'] : 'Jan';
        $surname = (isset($_POST['surname'])) ? $_POST['surname'] : 'Novák';
        $age = (isset($_POST['age'])) ? $_POST['age'] : '';
        $tel = (isset($_POST['tel'])) ? $_POST['tel'] : '+420 ';
    ?>
    <form method="POST" action="customers">
        <table class="table-borderless">
            <tr>
                <td>
                    <label>Jméno</label>
                    <input type="text" name="name" value="<?= $name ?>">
                </td>
                <td>
                    <label>Příjmení</label>
                    <input type="text" name="surname" value="<?= $surname ?>">
                </td>
            </tr>
            <tr>
                <td>
                    <label>Věk</label>
                    <input type="number" name="age" value="<?= $age ?>">
                </td>
                <td>
                    <label>Telefon</label>
                    <input type="tel" name="tel" value="<?= $tel ?>">
                </td>
            </tr>
            <tr>
                <td colspan="2" id="submit-td">
                    <input type="submit" value="Uložit" class="btn btn-secondary">
                </td>
            </tr>
        </table>
    </form>
</section>